FROM alpine:3.13.0 AS builder

RUN apk add --update --no-cache ca-certificates~=20191127 bash~=5.1 curl~=7.77


FROM alpine:3.13.0

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ARG BUILD_DIR
ARG BINARY_NAME

ENV GIN_MODE=release

COPY $BUILD_DIR/$BINARY_NAME /app

CMD ["/app"]
