version: 2.1

orbs:
  docker: banzaicloud/docker@0.0.7


workflows:
  version: 2
  ci:
    jobs:
      - docker/build:
          name: Docker build
          executor: docker/machine-dlc
          image: banzaicloud/allspark
          tag: ${CIRCLE_BRANCH//\//_}
          filters:
            branches:
              ignore: master

      - docker/custom-publish:
          name: Publish master image
          executor: docker/machine-dlc
          context: image-registries
          login:
            - docker/login
            - docker/ghcr-login
          push:
            - docker/push:
                registry: docker.io
                image: banzaicloud/allspark
                tag: master
            - docker/push:
                registry: ghcr.io
                image: banzaicloud/allspark
                tag: master
          requires:
            - build
          filters:
            branches:
              only: master

      - docker/custom-publish:
          name: Publish tagged & latest image
          executor: docker/machine-dlc
          context: image-registries
          login:
            - docker/login
            - docker/ghcr-login
          push:
            - docker/push:
                registry: docker.io
                image: banzaicloud/allspark
                tag: ${CIRCLE_TAG//\//_}
            - docker/push:
                registry: ghcr.io
                image: banzaicloud/allspark
                tag: ${CIRCLE_TAG//\//_}
            - docker/conditional-push:
                registry: docker.io
                image: banzaicloud/allspark
                tag: latest
                condition-steps:
                  - docker/version-check:
                      version: ${CIRCLE_TAG//\//_}
            - docker/conditional-push:
                registry: ghcr.io
                image: banzaicloud/allspark
                tag: latest
                condition-steps:
                  - docker/version-check:
                      version: ${CIRCLE_TAG//\//_}
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+(?:-(?:dev|rc|alpha|beta)\.[0-9]+)?$/
            branches:
              ignore: /.*/
